# Generated by Django 4.0.1 on 2022-01-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('account_name', models.CharField(help_text='Customer Account Name', max_length=255, verbose_name='Account Name')),
                ('account_number', models.CharField(default='000000000000', help_text='Number of the account', max_length=255, unique=True, verbose_name='Customer Account Number')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('customer_id', 'account_number')},
            },
        ),
    ]
