# Generated by Django 4.0.1 on 2022-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Transaction At'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='disable', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Disabled At'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Enabled At'),
        ),
    ]
